language: ruby
# NOTE: temporary workaround for Rubygems issue #763
before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
notifications:
  email: false